version: 2.1
workflows:
  my-workflow:
    jobs:
      - build-and-test:
          context: my-context

jobs:
  build-and-test:
    machine: linux
    steps:
      - checkout
      - run:
          name: echo $SECRET
          command: echo $SECRETs
